// ══════════════════════════════════════════════════════════════════════════════
// THE CORE SCAN — WHAT THE SCREEN SAYS
//
// Every sentence the scan screen can show, in both languages, in one place.
// Hebrew is the default language of the app and is written first-hand here,
// not derived from the English.
// ══════════════════════════════════════════════════════════════════════════════
import { formatPrice } from './utils';

// A price keeps its own left-to-right order inside a Hebrew sentence: ₪290, never 290₪.
const ltr = (s) => `⁦${s}⁩`;
/** ₪240–270: one currency sign for the pair. */
const range = (band) => ltr(band.low === band.high ? formatPrice(band.low) : `${formatPrice(band.low)}–${Number(band.high).toLocaleString()}`);

export const SCAN_COPY = {
  en: {
    close: 'Close',
    analyzing: 'Analyzing photo…',
    lookingAgain: 'Looking again…',
    pricing: 'Checking today\'s market prices…',
    identityConfidence: 'Identity confidence',
    priceConfidence: 'Price confidence',
    levels: { high: 'High', medium: 'Medium', low: 'Low' },
    recommended: 'Recommended listing price',
    expected: 'Expected selling range',
    approxLabel: 'Approximate selling range',
    approxNote: 'The exact model is not confirmed, so this is a range for the product family.',
    thin: (n) => (n === 1 ? 'Rough estimate: based on one second-hand reference.' : `Rough estimate: based on only ${n} second-hand references.`),
    abroadOnly: 'No Israeli second-hand prices were found; this rests on prices abroad.',
    conditionAdjusted: 'The price for this condition is an adjustment from the listings found, not taken from listings in this condition.',
    range,
    conditionLabel: 'Condition',
    conditions: { new_sealed: 'New / Sealed', like_new: 'Like new', good: 'Good', fair: 'Fair', poor: 'Poor' },
    appears: (c) => `Visible condition appears ${c}.`,
    sellFor: (price) => `Sell for ${price}`,
    sellAbout: (price) => `Sell for about ${price}`,
    sellOwnPrice: 'Sell at your own price',
    wrongItem: 'Wrong item?',
    whyPrice: 'Why this price?',
    whatFound: 'What I found',
    refine: 'For a more exact price',
    notSure: 'Not sure',
    takePhoto: 'Take the photo',
    uploadPhoto: 'Upload a photo',
    insufficient: (name) => `I identified this as ${name}, but I don't have enough reliable current second-hand evidence to give you a confident Israeli market price.`,
    retailContext: (price) => `New, it currently sells for about ${price} in Israel.`,
    noItem: 'I couldn\'t find an item to sell in this photo.',
    noItemHint: 'Take a photo with the item filling most of the frame.',
    retry: 'Try again',
    scanAgain: 'Scan another item',
    // "Wrong item?"
    correctTitle: 'What is it?',
    correctHint: 'Tell me in your own words: brand, model, variant.',
    correctPlaceholder: 'Actually this is a Logitech G Pro Wireless',
    correctCouldBe: 'Could it be one of these?',
    correctSubmit: 'Update',
    // "Why this price?"
    whyTitle: 'Why this price?',
    searchedOn: (date) => `Market searched on ${date}`,
    references: (n) => `${n} second-hand ${n === 1 ? 'reference' : 'references'}`,
    refSplit: (il, intl) => [il ? `${il} from Israel` : null, intl ? `${intl} from abroad` : null].filter(Boolean).join(' · '),
    exactSplit: (exact, close) => [exact ? `${exact} exact match` : null, close ? `${close} close comparable` : null].filter(Boolean).join(' · '),
    retailAnchor: (price) => `New in Israel: about ${price}`,
    setAside: (n) => `${n} other ${n === 1 ? 'result was' : 'results were'} set aside (a different model, an accessory, a part, or a price out of line).`,
    how: 'The price is calculated from these references, not chosen: the weighted middle of the second-hand prices, with asking prices reduced by 10% for negotiation.',
    intlAdjusted: (scale) => `Prices from abroad were scaled to Israeli price level (×${scale}), using the item's new price in both markets.`,
    intlUnadjusted: 'Prices from abroad are converted to shekels but not adjusted to Israeli price level.',
    conditionsHow: 'Prices for other conditions are a standard adjustment from Good condition, not separate market findings.',
    approximateWhy: 'The exact model is not confirmed, so the references are for the product family.',
    sources: 'Sources',
    kinds: { used_listing: 'Used', sold: 'Sold', refurbished: 'Refurbished', new_retail: 'New', price_guide: 'Price guide', other: 'Other' },
    matches: { exact: 'exact', close_comparable: 'comparable' },
    approx: (price) => `≈ ${price}`,
    noSources: 'No usable price sources were found.',
  },
  he: {
    close: 'סגירה',
    analyzing: 'מנתחים את התמונה…',
    lookingAgain: 'בודקים שוב…',
    pricing: 'בודקים מחירי שוק עדכניים…',
    identityConfidence: 'ביטחון בזיהוי',
    priceConfidence: 'ביטחון במחיר',
    levels: { high: 'גבוה', medium: 'בינוני', low: 'נמוך' },
    recommended: 'מחיר מומלץ לפרסום',
    expected: 'טווח מכירה צפוי',
    approxLabel: 'טווח מכירה משוער',
    approxNote: 'הדגם המדויק לא אומת, ולכן זהו טווח למשפחת המוצר.',
    thin: (n) => (n === 1 ? 'הערכה גסה: מבוססת על מקור יד שנייה אחד.' : `הערכה גסה: מבוססת על ${n} מקורות יד שנייה בלבד.`),
    abroadOnly: 'לא נמצאו מחירי יד שנייה בישראל; ההערכה נשענת על מחירים בחו״ל.',
    conditionAdjusted: 'המחיר למצב הזה הוא התאמה מהמודעות שנמצאו, ולא נלקח ממודעות במצב הזה.',
    range,
    conditionLabel: 'מצב הפריט',
    conditions: { new_sealed: 'חדש / באריזה', like_new: 'כמו חדש', good: 'טוב', fair: 'סביר', poor: 'גרוע' },
    appears: (c) => `לפי התמונה, המצב נראה ${c}.`,
    sellFor: (price) => `למכור ב־${ltr(price)}`,
    sellAbout: (price) => `למכור בכ־${ltr(price)}`,
    sellOwnPrice: 'למכור במחיר שלי',
    wrongItem: 'פריט שגוי?',
    whyPrice: 'למה המחיר הזה?',
    whatFound: 'מה מצאתי',
    refine: 'למחיר מדויק יותר',
    notSure: 'לא בטוח/ה',
    takePhoto: 'לצלם',
    uploadPhoto: 'להעלות תמונה',
    insufficient: (name) => `זיהיתי את הפריט כ־${ltr(name)}, אבל אין לי מספיק ראיות אמינות ועדכניות ממכירות יד שנייה כדי לתת מחיר שוק בטוח בישראל.`,
    retailContext: (price) => `חדש, הוא נמכר היום בישראל בכ־${ltr(price)}.`,
    noItem: 'לא מצאתי בתמונה פריט למכירה.',
    noItemHint: 'צלמו כך שהפריט ימלא את רוב התמונה.',
    retry: 'לנסות שוב',
    scanAgain: 'לסרוק פריט אחר',
    correctTitle: 'מה זה באמת?',
    correctHint: 'כתבו במילים שלכם: מותג, דגם, גרסה.',
    correctPlaceholder: 'זה בעצם Logitech G Pro Wireless',
    correctCouldBe: 'אולי אחד מאלה?',
    correctSubmit: 'עדכון',
    whyTitle: 'למה המחיר הזה?',
    searchedOn: (date) => `השוק נבדק בתאריך ${date}`,
    references: (n) => (n === 1 ? 'מקור אחד של יד שנייה' : `${n} מקורות של יד שנייה`),
    refSplit: (il, intl) => [il ? `${il} מישראל` : null, intl ? `${intl} מחו״ל` : null].filter(Boolean).join(' · '),
    exactSplit: (exact, close) => [exact ? `${exact} בהתאמה מדויקת` : null, close ? `${close} של פריט דומה` : null].filter(Boolean).join(' · '),
    retailAnchor: (price) => `מחיר חדש בישראל: כ־${ltr(price)}`,
    setAside: (n) => (n === 1 ? 'תוצאה אחת נוספת לא נכללה (דגם אחר, אביזר, חלק או מחיר חריג).' : `${n} תוצאות נוספות לא נכללו (דגם אחר, אביזר, חלק או מחיר חריג).`),
    how: 'המחיר מחושב מהמקורות האלה ולא נבחר: האמצע המשוקלל של מחירי היד השנייה, כשמחירי מודעות מופחתים ב־10% למיקוח.',
    intlAdjusted: (scale) => `מחירים מחו״ל הותאמו לרמת המחירים בישראל (×${scale}), לפי מחיר המוצר החדש בשני השווקים.`,
    intlUnadjusted: 'מחירים מחו״ל הומרו לשקלים אך לא הותאמו לרמת המחירים בישראל.',
    conditionsHow: 'המחירים למצבים האחרים הם התאמה קבועה ממצב "טוב", ולא ממצאי שוק נפרדים.',
    approximateWhy: 'הדגם המדויק לא אומת, ולכן המקורות הם של משפחת המוצר.',
    sources: 'מקורות',
    kinds: { used_listing: 'משומש', sold: 'נמכר', refurbished: 'מחודש', new_retail: 'חדש', price_guide: 'מחירון', other: 'אחר' },
    matches: { exact: 'מדויק', close_comparable: 'דומה' },
    approx: (price) => `≈ ${price}`,
    noSources: 'לא נמצאו מקורות מחיר שמישים.',
  },
};

export const scanCopy = (lang) => SCAN_COPY[lang === 'he' ? 'he' : 'en'];
